package game

import sdl "vendor:sdl2"

ROW :: 20
COL :: 10
BLOCK :: 30
GAME_NAME :: "Tetrio"

WINDOW_WIDTH :: BLOCK * 18
WINDOW_HEIGHT :: BLOCK * 22
WINDOW_X :: sdl.WINDOWPOS_CENTERED
WINDOW_Y :: sdl.WINDOWPOS_CENTERED
WINDOW_FLAGS :: sdl.WindowFlags{.SHOWN}

VIEWPORT_INFO_WIDTH :: BLOCK * 5
VIEWPORT_INFO_HEIGHT :: BLOCK * 4

FPS :: 60
TICKS_PER_FRAME: f64 = 1000.0 / cast(f64)FPS
